"""Build tools/i18n/glossary/<lang>.md (English UI label -> translated UI label) from the
backoffice locale files, so the docs use exactly the words the app shows.

  python3 tools/i18n/glossary.py --lang de
  python3 tools/i18n/glossary.py --lang de --locale-dir /path/to/client/app/i18n

Strings identical to English (= not translated yet in the app), strings with {{placeholders}}
and strings longer than 60 chars (sentences) are skipped. When the same English label has
several translations, the first key in locale-en.json order wins; the agent picks by context.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from common import ROOT

DEFAULT_LOCALE_DIR = ROOT.parent / "circuitauction-backoffice" / "client" / "app" / "i18n"
MAX_LEN = 60


def flatten(obj: dict, prefix: str = "") -> dict[str, object]:
    out: dict[str, object] = {}
    for k, v in obj.items():
        if isinstance(v, dict):
            out.update(flatten(v, f"{prefix}{k}."))
        else:
            out[f"{prefix}{k}"] = v
    return out


def glossary_pairs(en: dict, tr: dict) -> list[tuple[str, str]]:
    fe, ft = flatten(en), flatten(tr)
    pairs: dict[str, str] = {}
    for key, src in fe.items():
        dst = ft.get(key)
        if not isinstance(src, str) or not isinstance(dst, str):
            continue
        src, dst = src.strip(), dst.strip()
        if not src or src == dst or "{{" in src or len(src) > MAX_LEN:
            continue
        pairs.setdefault(src, dst)
    return sorted(pairs.items(), key=lambda kv: kv[0].lower())


def render(pairs: list[tuple[str, str]], lang: str) -> str:
    lines = [f"# UI glossary ({lang})", "",
             "Generated by `python3 tools/i18n/glossary.py --lang " + lang + "` from the backoffice",
             "`locale-en.json` / `locale-" + lang + ".json`. Do not edit by hand.", "",
             f"| English | {lang} |", "|---|---|"]
    lines += [f"| {e.replace('|', '/')} | {t.replace('|', '/')} |" for e, t in pairs]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--lang", required=True)
    ap.add_argument("--locale-dir", type=Path, default=DEFAULT_LOCALE_DIR)
    ap.add_argument("--out", type=Path, default=None)
    a = ap.parse_args(argv)
    en = json.loads((a.locale_dir / "locale-en.json").read_text(encoding="utf-8"))
    tr = json.loads((a.locale_dir / f"locale-{a.lang}.json").read_text(encoding="utf-8"))
    pairs = glossary_pairs(en, tr)
    out = a.out or ROOT / "tools" / "i18n" / "glossary" / f"{a.lang}.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(pairs, a.lang), encoding="utf-8")
    print(f"wrote {out} ({len(pairs)} terms)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
